import OpenAI from "openai";

interface CodeGenerationParams {
  title: string;
  description: string;
  language: string;
  difficulty: string;
}

interface CodeGenerationResult {
  code: string;
  explanation: string;
  language: string;
}

export class AICodeGenerationService {
  private openai: OpenAI | null = null;
  private readonly CODE_BLOCK_REGEX = /```[\w]*\n([\s\S]*?)```/;
  private readonly EXPLANATION_REGEX = /EXPLANATION:\s*([\s\S]*?)$/i;

  constructor() {
    const apiKey = process.env.OPENAI_API_KEY;
    if (apiKey) {
      this.openai = new OpenAI({ apiKey });
    }
  }

  async generateCode(
    params: CodeGenerationParams,
  ): Promise<CodeGenerationResult> {
    if (!this.openai) {
      // Fallback to mock implementation if no API key is configured
      return this.generateMockCode(params);
    }

    try {
      const prompt = this.buildPrompt(params);

      const completion = await this.openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [
          {
            role: "system",
            content:
              "You are an expert software engineer who writes clean, efficient, and well-documented code. Generate code based on the user's requirements and provide a brief explanation.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
        temperature: 0.7,
        max_tokens: 2000,
      });

      const response = completion.choices[0]?.message?.content || "";
      return this.parseResponse(response, params.language);
    } catch (error) {
      console.error("Error generating code with AI:", error);
      // Fallback to mock on error
      return this.generateMockCode(params);
    }
  }

  private sanitizeInput(input: string, maxLength: number): string {
    // Remove HTML tags, control characters, and limit length
    return input
      .replace(/[<>]/g, "") // Remove angle brackets to prevent HTML injection
      .replace(/[\x00-\x1F\x7F]/g, "") // Remove control characters
      .replace(/[{}[\]]/g, "") // Remove braces and brackets that could break prompt structure
      .trim()
      .slice(0, maxLength);
  }

  private buildPrompt(params: CodeGenerationParams): string {
    // Sanitize inputs more thoroughly to prevent prompt injection
    const sanitizedTitle = this.sanitizeInput(params.title, 100);
    const sanitizedDescription = this.sanitizeInput(params.description, 1000);
    
    // Validate that sanitized inputs still meet minimum requirements
    if (sanitizedTitle.length < 3 || sanitizedDescription.length < 10) {
      throw new Error("Input contains invalid characters");
    }
    
    return this.buildPromptTemplate(
      sanitizedTitle,
      sanitizedDescription,
      params.language,
      params.difficulty
    );
  }

  private buildPromptTemplate(
    title: string,
    description: string,
    language: string,
    difficulty: string
  ): string {
    return `Task: ${title}

Description: ${description}

Programming Language: ${language}
Difficulty Level: ${difficulty}

Please generate code that:
1. Implements the requirements described above
2. Follows best practices for ${language}
3. Is appropriate for ${difficulty} difficulty level
4. Includes comments explaining key parts

Format your response as:
CODE:
\`\`\`${language}
[your code here]
\`\`\`

EXPLANATION:
[Brief explanation of the implementation]`;
  }

  private parseResponse(
    response: string,
    language: string,
  ): CodeGenerationResult {
    // Extract code block using named regex
    const codeMatch = response.match(this.CODE_BLOCK_REGEX);
    const code = codeMatch ? codeMatch[1].trim() : response;

    // Extract explanation (text after EXPLANATION: or after code block)
    let explanation = "";
    const explanationMatch = response.match(this.EXPLANATION_REGEX);
    if (explanationMatch) {
      explanation = explanationMatch[1].trim();
    } else {
      // Try to get text after the code block
      const parts = response.split("```");
      if (parts.length > 2) {
        explanation = parts[2].trim();
      }
    }

    if (!explanation) {
      explanation =
        "Code generated successfully based on the provided requirements.";
    }

    return {
      code,
      explanation,
      language,
    };
  }

  private generateMockCode(params: CodeGenerationParams): CodeGenerationResult {
    const mockCode = this.getMockCodeByLanguage(params);

    return {
      code: mockCode,
      explanation: `This is a mock implementation for "${params.title}". In production, this would be generated by an AI model. Configure OPENAI_API_KEY environment variable to enable actual AI code generation.`,
      language: params.language,
    };
  }

  private getMockCodeByLanguage(params: CodeGenerationParams): string {
    const { title, description, language, difficulty } = params;

    const templates: Record<string, string> = {
      python: `"""
${title}

${description}

Difficulty: ${difficulty}
"""

def main():
    """Main function implementing the task."""
    # TODO: Implement the functionality
    print("Task: ${title}")
    print("Implementation pending...")
    pass

if __name__ == "__main__":
    main()`,

      javascript: `/**
 * ${title}
 * 
 * ${description}
 * 
 * Difficulty: ${difficulty}
 */

function main() {
  // TODO: Implement the functionality
  console.log('Task: ${title}');
  console.log('Implementation pending...');
}

main();`,

      typescript: `/**
 * ${title}
 * 
 * ${description}
 * 
 * Difficulty: ${difficulty}
 */

function main(): void {
  // TODO: Implement the functionality
  console.log('Task: ${title}');
  console.log('Implementation pending...');
}

main();`,

      swift: `//
//  ${title}
//
//  ${description}
//
//  Difficulty: ${difficulty}
//

import Foundation

func main() {
    // TODO: Implement the functionality
    print("Task: ${title}")
    print("Implementation pending...")
}

main()`,

      java: `/**
 * ${title}
 * 
 * ${description}
 * 
 * Difficulty: ${difficulty}
 */

public class Main {
    public static void main(String[] args) {
        // TODO: Implement the functionality
        System.out.println("Task: ${title}");
        System.out.println("Implementation pending...");
    }
}`,
    };

    return templates[language] || templates.javascript;
  }
}

export const aiService = new AICodeGenerationService();
